name: Task07_Pancreas
task: segmentation

modality: CT
datalist: ./datafolds/msd_task07_pancreas_folds.json # list of files
dataroot: /data/Task07_Pancreas # data location

multigpu: True

class_names: [val_acc_vessel, val_acc_tumor]